import type {
  LaundryMonthExportPayload,
  LaundryYearExportPayload,
} from './laundrySalesReportData';

type SheetCell = string | number;
type SheetRow = SheetCell[];
type XlsxMerge = { s: { r: number; c: number }; e: { r: number; c: number } };

type XlsxLib = {
  utils: {
    book_new: () => unknown;
    aoa_to_sheet: (data: SheetRow[]) => Record<string, unknown> & { '!cols'?: { wch: number }[]; '!merges'?: XlsxMerge[] };
    book_append_sheet: (wb: unknown, ws: unknown, name: string) => void;
  };
  writeFile: (wb: unknown, filename: string) => void;
};

const XLSX_CDN = 'https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';

let xlsxLoad: Promise<XlsxLib> | null = null;

function loadXlsx(): Promise<XlsxLib> {
  if (xlsxLoad) return xlsxLoad;
  xlsxLoad = new Promise((resolve, reject) => {
    const w = window as Window & { XLSX?: XlsxLib };
    if (w.XLSX) {
      resolve(w.XLSX);
      return;
    }
    const script = document.createElement('script');
    script.src = XLSX_CDN;
    script.async = true;
    script.onload = () => (w.XLSX ? resolve(w.XLSX) : reject(new Error('SheetJS failed to load')));
    script.onerror = () => reject(new Error('SheetJS failed to load'));
    document.head.appendChild(script);
  });
  return xlsxLoad;
}

function formatDateTime(d: Date): string {
  return `${d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })} ${d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })}`;
}

function timelineDateLabel(isoDay: string): string {
  const d = new Date(isoDay + 'T12:00:00');
  return d.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' });
}

function roundMoney(n: number): number {
  return Math.round(n * 100) / 100;
}

function pushBlank(rows: SheetRow[]) {
  rows.push([]);
}

function pushSectionTitle(rows: SheetRow[], title: string) {
  pushBlank(rows);
  rows.push([title]);
}

function buildMonthRows(payload: LaundryMonthExportPayload): { rows: SheetRow[]; merges: XlsxMerge[] } {
  const { monthLabel, generatedAt, data, transactions } = payload;
  const rows: SheetRow[] = [];
  const merges: XlsxMerge[] = [];

  rows.push(['Zoda Laundry — Monthly Sales Report']);
  merges.push({ s: { r: 0, c: 0 }, e: { r: 0, c: 4 } });
  rows.push(['Report period', monthLabel]);
  rows.push(['Generated on', formatDateTime(generatedAt)]);

  pushSectionTitle(rows, 'SUMMARY');
  rows.push(['Metric', 'Value']);
  rows.push(['Total sales (PHP)', roundMoney(data.totalSales)]);
  rows.push(['POS transactions', data.totalOrderCount]);
  rows.push([
    'Average ticket (PHP)',
    data.totalOrderCount > 0 ? roundMoney(data.totalSales / data.totalOrderCount) : 0,
  ]);

  pushSectionTitle(rows, 'DAILY BREAKDOWN');
  rows.push(['Date', 'Sales (PHP)']);
  for (const pt of data.timeline) {
    rows.push([timelineDateLabel(pt.key), roundMoney(pt.total)]);
  }

  pushSectionTitle(rows, 'TOP SERVICES');
  rows.push(['#', 'Service', 'Qty', 'Revenue (PHP)']);
  if (data.topProducts.length === 0) {
    rows.push(['', 'No sales in this period', '', '']);
  } else {
    data.topProducts.forEach((p, i) => {
      rows.push([i + 1, p.name, p.units, roundMoney(p.revenue)]);
    });
  }

  pushSectionTitle(rows, 'ALL TRANSACTIONS');
  rows.push(['Date & time', 'Customer', 'Receipt #', 'Amount (PHP)', 'Services']);
  if (transactions.length === 0) {
    rows.push(['No transactions in this period', '', '', '', '']);
  } else {
    for (const t of transactions) {
      rows.push([
        formatDateTime(t.at),
        t.customerName,
        t.receiptNo,
        roundMoney(t.amount),
        t.services || '—',
      ]);
    }
  }

  rows.push([]);
  rows.push(['Generated by Zoda Admin — Laundry']);

  return { rows, merges };
}

function buildYearRows(payload: LaundryYearExportPayload): { rows: SheetRow[]; merges: XlsxMerge[] } {
  const { year, generatedAt, months, yearTotals, topServices } = payload;
  const rows: SheetRow[] = [];
  const merges: XlsxMerge[] = [];

  rows.push(['Zoda Laundry — Annual Sales Report']);
  merges.push({ s: { r: 0, c: 0 }, e: { r: 0, c: 4 } });
  rows.push(['Report year', year]);
  rows.push(['Generated on', formatDateTime(generatedAt)]);

  pushSectionTitle(rows, 'YEAR TOTALS');
  rows.push(['Metric', 'Value']);
  rows.push(['Total sales (PHP)', roundMoney(yearTotals.totalSales)]);
  rows.push(['POS transactions', yearTotals.txnCount]);

  pushSectionTitle(rows, 'MONTHLY SUMMARY');
  rows.push(['Month', 'Sales (PHP)', 'Transactions']);
  for (const m of months) {
    rows.push([m.monthLabel, roundMoney(m.total), m.txnCount]);
  }

  pushSectionTitle(rows, 'TOP SERVICES (FULL YEAR)');
  rows.push(['#', 'Service', 'Qty', 'Revenue (PHP)']);
  if (topServices.length === 0) {
    rows.push(['', 'No sales this year', '', '']);
  } else {
    topServices.forEach((p, i) => {
      rows.push([i + 1, p.name, p.units, roundMoney(p.revenue)]);
    });
  }

  rows.push([]);
  rows.push(['Generated by Zoda Admin — Laundry']);

  return { rows, merges };
}

async function writeWorkbook(rows: SheetRow[], merges: XlsxMerge[], sheetName: string, filename: string) {
  const XLSX = await loadXlsx();
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!cols'] = [{ wch: 34 }, { wch: 18 }, { wch: 14 }, { wch: 16 }, { wch: 42 }];
  if (merges.length) ws['!merges'] = merges;
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, sheetName.slice(0, 31));
  const out = filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`;
  XLSX.writeFile(wb, out);
}

export async function downloadLaundryMonthSpreadsheet(payload: LaundryMonthExportPayload, filename: string) {
  const { rows, merges } = buildMonthRows(payload);
  await writeWorkbook(rows, merges, 'Laundry Monthly', filename);
}

export async function downloadLaundryYearSpreadsheet(payload: LaundryYearExportPayload, filename: string) {
  const { rows, merges } = buildYearRows(payload);
  await writeWorkbook(rows, merges, 'Laundry Annual', filename);
}
