import { SALES_CATEGORY_LABELS, type SalesCategoryKey } from './productCategory';
import type { MonthExportPayload, YearExportPayload } from './salesReportData';

type SheetCell = string | number;
type SheetRow = SheetCell[];
type XlsxMerge = { s: { r: number; c: number }; e: { r: number; c: number } };

type XlsxLib = {
  utils: {
    book_new: () => unknown;
    aoa_to_sheet: (data: SheetRow[]) => Record<string, unknown> & { '!cols'?: { wch: number }[]; '!merges'?: XlsxMerge[] };
    book_append_sheet: (wb: unknown, ws: unknown, name: string) => void;
  };
  writeFile: (wb: unknown, filename: string) => void;
};

const XLSX_CDN = 'https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';

let xlsxLoad: Promise<XlsxLib> | null = null;

function loadXlsx(): Promise<XlsxLib> {
  if (xlsxLoad) return xlsxLoad;
  xlsxLoad = new Promise((resolve, reject) => {
    const w = window as Window & { XLSX?: XlsxLib };
    if (w.XLSX) {
      resolve(w.XLSX);
      return;
    }
    const existing = document.querySelector(`script[src="${XLSX_CDN}"]`);
    if (existing) {
      existing.addEventListener('load', () => (w.XLSX ? resolve(w.XLSX) : reject(new Error('SheetJS failed to load'))));
      existing.addEventListener('error', () => reject(new Error('SheetJS failed to load')));
      return;
    }
    const script = document.createElement('script');
    script.src = XLSX_CDN;
    script.async = true;
    script.onload = () => {
      if (w.XLSX) resolve(w.XLSX);
      else reject(new Error('SheetJS failed to load'));
    };
    script.onerror = () => reject(new Error('SheetJS failed to load'));
    document.head.appendChild(script);
  });
  return xlsxLoad;
}

function formatDateTime(d: Date): string {
  return `${d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })} ${d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })}`;
}

function timelineDateLabel(isoDay: string): string {
  const d = new Date(isoDay + 'T12:00:00');
  return d.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' });
}

function pushBlank(rows: SheetRow[]) {
  rows.push([]);
}

function pushSectionTitle(rows: SheetRow[], title: string) {
  pushBlank(rows);
  rows.push([title]);
}

function buildMonthRows(payload: MonthExportPayload): { rows: SheetRow[]; merges: XlsxMerge[] } {
  const { monthLabel, generatedAt, data, transactions } = payload;
  const cats = Object.keys(SALES_CATEGORY_LABELS) as SalesCategoryKey[];
  const rows: SheetRow[] = [];
  const merges: XlsxMerge[] = [];

  rows.push(['Zoda WRS — Monthly Sales Report']);
  merges.push({ s: { r: 0, c: 0 }, e: { r: 0, c: 4 } });
  rows.push(['Report period', monthLabel]);
  rows.push(['Generated on', formatDateTime(generatedAt)]);

  pushSectionTitle(rows, 'SUMMARY');
  rows.push(['Metric', 'Value']);
  rows.push(['Total sales (PHP)', roundMoney(data.totalSales)]);
  rows.push(['Online sales (PHP)', roundMoney(data.onlineSales)]);
  rows.push(['Walk-in sales (PHP)', roundMoney(data.walkInSales)]);
  rows.push(['Online orders (paid)', data.onlineOrderCount]);
  rows.push(['Walk-in transactions', data.walkInTxnCount]);
  rows.push(['Paid orders', data.paidOrders]);
  rows.push(['Unpaid orders', data.unpaidOrders]);

  pushSectionTitle(rows, 'DAILY BREAKDOWN');
  rows.push(['Date', 'Online (PHP)', 'Walk-in (PHP)', 'Total (PHP)']);
  for (const pt of data.timeline) {
    rows.push([timelineDateLabel(pt.key), roundMoney(pt.online), roundMoney(pt.walkIn), roundMoney(pt.total)]);
  }

  pushSectionTitle(rows, 'SALES BY CATEGORY');
  rows.push(['Category', 'Amount (PHP)']);
  for (const k of cats) {
    rows.push([SALES_CATEGORY_LABELS[k], roundMoney(data.categoryTotals[k])]);
  }

  pushSectionTitle(rows, 'TOP SELLING PRODUCTS');
  rows.push(['#', 'Product', 'Units sold', 'Revenue (PHP)']);
  if (data.topProducts.length === 0) {
    rows.push(['', 'No sales in this period', '', '']);
  } else {
    data.topProducts.forEach((p, i) => {
      rows.push([i + 1, p.name, p.units, roundMoney(p.revenue)]);
    });
  }

  pushSectionTitle(rows, 'ALL TRANSACTIONS');
  rows.push(['Date & time', 'Type', 'Status', 'Amount (PHP)', 'Products']);
  if (transactions.length === 0) {
    rows.push(['No transactions in this period', '', '', '', '']);
  } else {
    for (const t of transactions) {
      rows.push([
        formatDateTime(t.at),
        t.type,
        t.status,
        roundMoney(t.amount),
        t.products || '—',
      ]);
    }
  }

  rows.push([]);
  rows.push(['Generated by Zoda WRS Admin']);

  return { rows, merges };
}

function buildYearRows(payload: YearExportPayload): { rows: SheetRow[]; merges: XlsxMerge[] } {
  const { year, generatedAt, months, yearTotals, categoryTotals, topProducts } = payload;
  const cats = Object.keys(SALES_CATEGORY_LABELS) as SalesCategoryKey[];
  const rows: SheetRow[] = [];
  const merges: XlsxMerge[] = [];

  rows.push(['Zoda WRS — Annual Sales Report']);
  merges.push({ s: { r: 0, c: 0 }, e: { r: 0, c: 5 } });
  rows.push(['Report year', year]);
  rows.push(['Generated on', formatDateTime(generatedAt)]);

  pushSectionTitle(rows, 'YEAR TOTALS');
  rows.push(['Metric', 'Value']);
  rows.push(['Total sales (PHP)', roundMoney(yearTotals.totalSales)]);
  rows.push(['Online sales (PHP)', roundMoney(yearTotals.onlineSales)]);
  rows.push(['Walk-in sales (PHP)', roundMoney(yearTotals.walkInSales)]);
  rows.push(['Online orders', yearTotals.onlineOrders]);
  rows.push(['Walk-in transactions', yearTotals.walkInTxns]);

  pushSectionTitle(rows, 'MONTHLY SUMMARY');
  rows.push(['Month', 'Online (PHP)', 'Walk-in (PHP)', 'Total (PHP)', 'Online orders', 'Walk-in txns']);
  for (const m of months) {
    rows.push([
      m.monthLabel,
      roundMoney(m.online),
      roundMoney(m.walkIn),
      roundMoney(m.total),
      m.onlineOrders,
      m.walkInTxns,
    ]);
  }

  pushSectionTitle(rows, 'SALES BY CATEGORY (FULL YEAR)');
  rows.push(['Category', 'Amount (PHP)']);
  for (const k of cats) {
    rows.push([SALES_CATEGORY_LABELS[k], roundMoney(categoryTotals[k])]);
  }

  pushSectionTitle(rows, 'TOP PRODUCTS (FULL YEAR)');
  rows.push(['#', 'Product', 'Units', 'Revenue (PHP)']);
  if (topProducts.length === 0) {
    rows.push(['', 'No sales this year', '', '']);
  } else {
    topProducts.forEach((p, i) => {
      rows.push([i + 1, p.name, p.units, roundMoney(p.revenue)]);
    });
  }

  rows.push([]);
  rows.push(['Generated by Zoda WRS Admin']);

  return { rows, merges };
}

function roundMoney(n: number): number {
  return Math.round(n * 100) / 100;
}

function applySheetLayout(ws: ReturnType<XlsxLib['utils']['aoa_to_sheet']>) {
  ws['!cols'] = [
    { wch: 34 },
    { wch: 18 },
    { wch: 14 },
    { wch: 16 },
    { wch: 42 },
    { wch: 14 },
  ];
}

async function writeWorkbook(rows: SheetRow[], merges: XlsxMerge[], sheetName: string, filename: string) {
  const XLSX = await loadXlsx();
  const ws = XLSX.utils.aoa_to_sheet(rows);
  applySheetLayout(ws);
  if (merges.length) ws['!merges'] = merges;
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, sheetName.slice(0, 31));
  const out = filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`;
  XLSX.writeFile(wb, out);
}

export async function downloadMonthSpreadsheet(payload: MonthExportPayload, filename: string) {
  const { rows, merges } = buildMonthRows(payload);
  await writeWorkbook(rows, merges, 'Monthly Report', filename);
}

export async function downloadYearSpreadsheet(payload: YearExportPayload, filename: string) {
  const { rows, merges } = buildYearRows(payload);
  await writeWorkbook(rows, merges, 'Annual Report', filename);
}
